### ISSUE TITLE
Melhor persistência

### ISSUE THREAD

**Issue by cadusilva** [amosbatista/ursal-acessivel#16]
Com as atualizações do bot, mas não especificamente a última, ele costuma verificar a timeline outra vez, retornando a toots com cerca de três meses, mesmo que eles já tenham sido vistos e notificados anteriormente. É como se o bot esquecesse dos arquivos persistentes e os sobrescrevesse, retornando para a estaca zero.

Sugiro então alguma mudança no algoritmo de persistência, algo como um `lastID` para o bot lembrar em qual ID de toot ele parou na última verificação, evitando floodar os usuários com notificações repetidas para posts antigos.

**Comment by amosbatista** [comment]
Olá.

Hoje, eu uso o parâmetro `min_id` para isto. Exemplo:
`https://ursal.zone/api/v1/timelines/public?local=true&only_media=true&limit=500&min_id=1231807123132`

Eu salvo o `min-id` no arquivo `timeline.json`. O problema é caso você perder este arquivo.
Um outro problema também é que o arquivo *está no repositório*. Ou seja, ele vai ser sobrescrito.

Então, precisa-se tirar este arquivo, para ele não sobrescrever.

**Comment by amosbatista** [comment]
Correção realizada na PR https://github.com/amosbatista/ursal-acessivel/pull/20, para remover tudo que estava dentro da pasta `/data`.

**Comment by cadusilva** [comment]
Obrigado, vou testar o novo código!

**Comment by cadusilva** [comment]
Meu `docker-compose.yml` (na forma de um Portainer Stacks):

```
version: '3.3'
services:
    acessivel:
        init: true
        container_name: acessivel
        image: code.bolha.one/bolha/acessivel:latest
        restart: unless-stopped
        environment:
            MASTODON_KEY: ABCDXYZ
            INSTANCE_URL: bolha.one
            INSTANCE_NAME: Bolha.one
            DM_MSG: "Alto lá! :policia: \n\nCom licença, @@$${post.user.userName}.\n\nReparei que este post ($${post.url}) tem uma imagem ou vídeo sem descrição. Como na $${process.env.INSTANCE_NAME} temos muito apreço por abrir as portas e incluir pessoas com deficiência visual, gostaria de reforçar com você este acordo de acessibilidade.\n\nPor favor, veja se é possível revisar e editar seu toot (via app ou web), adicionando descrição nas mídias.\n\nMuito obrigado por sua compreensão e apoio!"
            NODE_ENV: production
            TZ: "America/Recife"
        volumes:
            - /data/acessivel:/app/dist
            - /data/acessivel/data:/app/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
```

Imagem recém compilada a partir do código mais recente deste repositório. Apesar disso, ao ser iniciado, ele volta a vasculhar toots de novembro e fica mandando notificações para posts antigos.
